spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.254.28:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mapper/pms/*.xml
  #数据库主键自增
  global-config:
    db-config:
      id-type: auto
server:
  port: 15000